# Site settings
title: codingThoughts
description: > # this means to ignore newlines until "baseurl:"
  a blog by Thomas Holst
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tholst.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  tholst
encoding: utf-8

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge